config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#home'

  get 'user', to: 'user#show'
  get 'users/password/new', to: 'devise/passwords#new', as: 'password_reset'
  get 'log_out', to: 'home#log_out_button'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up/send', to: 'registrations#sign_up'
  get 'login', to: 'sessions#new'
  post 'login/send', to: 'sessions#login'
  get 'reset_password_email', to: 'passwords#new'
  post 'reset_password_email_setup', to: 'passwords#reset_password_email_setup'
  get 'reset_password', to: 'passwords#edit'
  post 'reset_password_setup', to: 'passwords#reset_password_setup'
  get 'create_event', to: 'events#new'
  post 'create_event/send', to: 'events#generate_event'
  get 'update_event', to: 'events#edit'
  post 'update_event/send', to: 'events#update_generated_event'
  post 'delete_event_setup', to: 'home#delete_event_setup', as: 'delete_event'
end

app/controllers/home_controller.rb
require "uri"
require "net/http"
require "cgi"

class HomeController < ApplicationController
    def home
        @invited_events = get_my_events(session[:user_id])
        @created_events = get_my_created_events(session[:user_id])
    end

    def log_out_button
        log_out
    end

end

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <section class="content">
    <body>
        <%= yield %>
        <% flash.each do |message_type, message| %>
          <div class="alert col-sm-10 offset-sm-1 error_message alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
        
        <% if session[:logged_in] %>
          <div class="row">
            <% if @invited_events != nil %>
            <div class="col-sm-10 offset-sm-1 text-box white-text">
              <h3 class="text-center"> Invited Events </h3>
              <table class="table white-text">
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                  <th scope="col">Scheduled For</th>
                  <th scope="col">Creator</th>
                  <th scope="col">Invited Users</th>
                </tr>
                <% @invited_events.each do |event| %>
                  <tr>
                    <td><%= event["title"] %></td>
                    <td><%= event["description"] %></td>
                    <td><%= event["scheduledAt"] %></td>
                    <td><%= event["creator"] %></td>
                    <td><% event["invitees"].each do |user| %><%= user%> <% end %></td>
                  </tr>
                <% end %>
              </table>
            </div>
            <% else %>
                <% if @created_events != nil %>
                  <div class="col-sm-10 offset-sm-1 text-box white-text">
                    <h3 class="text-center"> Invited Events </h3>
                    <p class="text-center">Events that you have been invited to will appear here</p>
                  </div>
                    
                <% else %>
                  <div class="col-sm-4 offset-sm-2 text-box white-text">
                    <h3 class="text-center"> Invited Events </h3>
                    <p class="text-center">Events that you have been invited to will appear here</p>
                  </div>
                <% end %>
            <% end %>
            <% if @created_events != nil %>
            <div class="col-sm-10 offset-sm-1 text-box white-text">
              <h3 class="text-center"> Created Events </h3>

              <table class="table white-text">
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                  <th scope="col">Scheduled For</th>
                  <th scope="col">Invited Users</th>
                  <th scope="col"></th>
                  <th scope="col"></th>

                </tr>
                <% @created_events.each do |event| %>
                  <tr>
                    <td><%= event["title"] %></td>
                    <td><%= event["description"] %></td>
                    <td><%= event["scheduledAt"] %></td>
                    <td><% event["invitees"].each do |user| %><%= user%> <% end %></td>
                    <td><%= link_to "Edit Event", update_event_path(id: event["id"]), class:"btn btn-info"%></td>
                    <td><%= link_to "Delete Event", delete_event_path(event), method: 'post', class:"btn btn-danger"%></td>

                  </tr>
                <% end %>
              </table>
            </div>
            <% else %>
              <% if @invited_events != nil %>
                <div class="col-sm-10 offset-sm-1 text-box white-text text-center">
                  <h3> Create An Event </h3>
                  <p>Schedule your first event and invite some people</p>
                  <%= link_to "Create Event", create_event_path, class: "btn btn-info"%>
                </div>
                
              <% else %>
                <div class="col-sm-4 text-box white-text text-center">
                  <h3> Create An Event </h3>
                  <p>Schedule your first event and invite some people</p>
                  <%= link_to "Create Event", create_event_path, class: "btn btn-info"%>
                </div>
              <% end %>

                  
            <% end %>
          </div>
        <% end %>
    </body>
  </section>
</html>