config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#home'

  get 'user', to: 'user#show'
  get 'users/password/new', to: 'devise/passwords#new', as: 'password_reset'
  get 'log_out', to: 'home#log_out_button'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up/send', to: 'registrations#sign_up'
  get 'login', to: 'sessions#new'
  post 'login/send', to: 'sessions#login'
  get 'reset_password_email', to: 'passwords#new'
  post 'reset_password_email_setup', to: 'passwords#reset_password_email_setup'
  get 'reset_password', to: 'passwords#edit'
  post 'reset_password_setup', to: 'passwords#reset_password_setup'
  get 'create_event', to: 'events#new'
  post 'create_event/send', to: 'events#generate_event'
  get 'update_event', to: 'events#edit'
  post 'update_event/send', to: 'events#update_generated_event'
  post 'delete_event_setup', to: 'home#delete_event_setup', as: 'delete_event'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def new
        @new_event_validation = EventValidation.new
        @new_event_error = ""
    end
    
    def edit
        @update_event_validation = EventValidation.new
        @update_event_error = ""
    end


    def generate_event
        @new_event_validation = EventValidation.new(params["new_event_validation"].permit(:title, :description, :active, :scheduledAtTime, :scheduledAtDate, :creator, :invitees))
        invitees_string = params["new_event_validation"]["invitees"].split(", ")
        invitees = get_ids(invitees_string)
        if invitees.nil?
            @new_event_error = "One or more of the users were not found"
            @new_event_validation = EventValidation.new()
            render 'new', status: :unprocessable_entity            
        else 

            @new_event_validation.invitees = invitees
            @new_event_validation.scheduledAt = "#{@new_event_validation.scheduledAtDate} #{@new_event_validation.scheduledAtTime}".to_datetime
            if @new_event_validation.valid?
                create_event(@new_event_validation)
                redirect_to root_path
            else
                puts @new_event_validation.errors.full_messages
                render 'new', status: :unprocessable_entity
            end
        end 
    end

    def update_generated_event
        @update_event_validation = EventValidation.new(params["update_event_validation"].permit(:id, :title, :description, :active, :scheduledAtTime, :scheduledAtDate, :creator, :invitees))
        invitees_string = params["update_event_validation"]["invitees"].split(", ")
        invitees = get_ids(invitees_string)
        if invitees.nil?
            @update_event_error = "One or more of the users were not found"
            
            redirect_to root_path, danger: @update_event_error    
        else 
            @update_event_validation.invitees = invitees
            @update_event_validation.scheduledAt = "#{@update_event_validation.scheduledAtDate} #{@update_event_validation.scheduledAtTime}".to_datetime
            if @update_event_validation.valid?
                update_event(@update_event_validation)
                redirect_to root_path
            else
                puts @update_event_validation.errors.full_messages
                render 'edit', status: :unprocessable_entity
            end
        end
    end
    
end

app/views/events/edit.html.erb
<body>
  <div class="row pt-5">
    <div class="col-md-6 offset-md-3 text-box">
      <h3 class="text-center", style="color: White;">Edit Event</h3>

      <%= form_for @update_event_validation, as: :update_event_validation, url: update_event_send_path do |f| %>
        <%= f.hidden_field :id, value: params["id"] %>
        
        <div class = "paragraph">
          <div class="field row", style="margin-top: 10px;">
            <%= f.label :title, "Title:", class: "form-label col-sm-4 text-sm-end" %><br />
            <%= f.text_field :title, class: "col-sm-7", required: true %>
          </div>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :description, "Description:", class: "form-label col-sm-4 text-sm-end" %><br />
            <%= f.text_field :description, class:"col-sm-7", required: true %>
          </div>

          <%= f.hidden_field :active, value: true %>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :scheduledAtTime, "Time", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.time_field :scheduledAtTime, class:"col-sm-7", required: true %>
          </div>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :scheduledAtDate, "Date", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.date_field :scheduledAtDate, class:"col-sm-7", required: true %>
          </div>

          <%= f.hidden_field :creator, value: session[:user_id] %>
          
          <div class="field row", style="margin-top: 10px;">
            <%= f.label :invitees, "Invites:", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.text_field :invitees, class:"col-sm-7", required: true %>
          </div> 
          <% if @update_event_error != "" %>
              <div class="row field">
                <div class="alert alert-danger error_message offset-sm-4 col-sm-7" role="alert">
                  <%= @update_event_error %>
                </div>
              </div>
          <% end %>


          <div class="actions text-center">
            <%= f.submit "Update Event", class: "btn btn-success text-center margin_top" %>
          </div>
        </div>
      <% end %>
    </div> 
  </div>   
</body>

app/views/events/new.html.erb
<body>
  <div class="row pt-5">
    <div class="col-md-6 offset-md-3 text-box">
      <h3 class="text-center", style="color: White;">Create Event</h3>

      <%= form_for @new_event_validation, as: :new_event_validation, url: create_event_send_path do |f| %>
        <div class="paragraph">
          <div class="field row", style="margin-top: 10px;">
            <%= f.label :title, "Title:", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.text_field :title, class:"col-sm-7", required: true %>
          </div>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :description, "Description:", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.text_field :description, class:"col-sm-7", required: true %>
          </div>

          <%= f.hidden_field :active, value: true %>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :scheduledAtTime, "Time", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.time_field :scheduledAtTime, class:"col-sm-7", required: true %>
          </div>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :scheduledAtDate, "Date", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.date_field :scheduledAtDate, class:"col-sm-7", required: true %>
          </div>

          <%= f.hidden_field :creator, value: session[:user_id] %>

          <div class="field row", style="margin-top: 10px;">
            <%= f.label :invitees, "Invites:", class: "form-label col-sm-4 text-sm-end" %>
            <%= f.text_field :invitees, class:"col-sm-7", required: true %>
          </div>
          <% if @new_event_error != "" %>
              <div class="row field">
                <div class="alert alert-danger error_message offset-sm-4 col-sm-7" role="alert">
                  <%= @new_event_error %>
                </div>
              </div>
          <% end %>  

          <div class="actions text-center">
            <%= submit_tag "Create Event", class: "btn btn-success text-center margin_top" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>