config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#home'

  get 'user', to: 'user#show'
  get 'users/password/new', to: 'devise/passwords#new', as: 'password_reset'
  get 'log_out', to: 'home#log_out_button'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up/send', to: 'registrations#sign_up'
  get 'login', to: 'sessions#new'
  post 'login/send', to: 'sessions#login'
  get 'reset_password_email', to: 'passwords#new'
  post 'reset_password_email_setup', to: 'passwords#reset_password_email_setup'
  get 'reset_password', to: 'passwords#edit'
  post 'reset_password_setup', to: 'passwords#reset_password_setup'
  get 'create_event', to: 'events#new'
  post 'create_event/send', to: 'events#generate_event'
  get 'update_event', to: 'events#edit'
  post 'update_event/send', to: 'events#update_generated_event'
  post 'delete_event_setup', to: 'home#delete_event_setup', as: 'delete_event'
end

app/views/layouts/_header.html.erb
<div class="nav nav-masthead justify-content-end">
    <%= link_to "Home", root_path, class: 'nav-link active' %>
    <% if session[:logged_in] %>
        <%= link_to "Create Event", create_event_path, class: 'nav-link' %>
        <%= link_to "Log out", log_out_path, class: 'nav-link' %>
    <% else %>
        <%= link_to "Login", login_path,  class: 'nav-link' %>
        <%= link_to "Sign up", sign_up_path,  class: 'nav-link' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>    
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
  </head>
  <section class="content">
  
    <body>
      <%= render "layouts/header" %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></pw w>
    </body>
    
  </section>
</html>